### ISSUE TITLE
Multicast UDP Support

### ISSUE THREAD

**Issue by taswhe** [aL3891/RioSharp#1]
Hi Allan, it would be great if we also have multicast UDP support!

**Comment by aL3891** [comment]
I'm actually working on that, its basically implemented but I havent tested it fully yet. I've been a little sidetracked the last few days but I hope i'll be able to get it out within a few days :)

**Comment by aL3891** [comment]
Multicast is now implemented! check out the new udp sample too see how to do use it :)

**Comment by taswhe** [comment]
Hi Allan, I finally got to test your code. It worked for receiving multicast traffic but it seems to suffer 20% packet loss on a not-too-busy network.

My code is essentially this:
~~~C#
            sendPool = new RioFixedBufferPool(10, 1440);
            recvPool = new RioFixedBufferPool(10, 1440);
            sockPool = new RioConnectionlessSocketPool(sendPool, recvPool, ADDRESS_FAMILIES.AF_INET, SOCKET_TYPE.SOCK_DGRAM, PROTOCOL.IPPROTO_UDP);
            sock = sockPool.Bind(new IPEndPoint(IPAddress.Any, port)); //, reuseAddress:true);
            sock.JoinMulticastGroup(IP);
            segm = new RioSegmentReader(sock);
            segm.OnIncommingSegment = OnIncomingSegment;
~~~
and
~~~C#
        private unsafe void OnIncomingSegment(RioBufferSegment s)
        {
            try
            {
                uint n = (uint)s.CurrentContentLength;
                fixed (byte* a = data) System.Runtime.CompilerServices.Unsafe.CopyBlock(a, s.Datapointer, n);
                // some action on "data" buffer to track message sequence number
            }
            catch (Exception e) { ... }
        }
~~~

Am I using the library the right way?

I understand that this library is no longer in active development. But being the only RIO implementation for multicast UDP sockets, I really wish it could work.

**Comment by aL3891** [comment]
Cool, glad it's useful to someone :) 
That looks correct, you might be running out of slots in the pool, you could try and increase the size of the RioFixedBufferPool. Also by default the incoming segment callback runs on the rio receive thread so if you take too long there that might also cause problems,
