### ISSUE TITLE
Consider providing unsafe Write/Read for RioBufferSegment

### ISSUE THREAD

**Issue by Scooletz** [aL3891/RioSharp#2]
Have you considered providing unsafe versions of:
- `RioBufferSegment.Write`
- `RioBufferSegment.Read`

that could be used by code working with already unsafe memory chunks? This with combination of using `RioSocket.Send` could enable to send data with zero-copy/no-allocations when using either Spans/Slices or good old-fashioned `stackalloc`. In my case, I could use it in https://github.com/Scooletz/SewingMachine/pull/4

**Comment by aL3891** [comment]
I dot quite remember why I don't have those, although there is a public Datapointer field that you can use :)

I'd be fine with having them though, but as I said in the other thread I really recommend checking out the pipelines work going on in the corefxlab repo, it has primitives that are a lot more thought through than mine :) 

Join it on gitter as well, there are a few of us who hang out there pretty regularly if you have questions!

**Comment by Scooletz** [comment]
Thx for clarification. Closing it.
