### ISSUE TITLE
UDP sample not working

### ISSUE THREAD

**Issue by buybackoff** [aL3891/RioSharp#5]
I get WSAEINVAL 10022 at [this line](https://github.com/aL3891/RioSharp/blob/4fdb3b5426ecab3ce60cccda2289bb8a1bc2cd14/RioSharp/RioSocket.cs#L122).

The sample is 2+ years old so the main question is if it is supposed to work as of now? And if it does then what could be wrong?

**Comment by buybackoff** [comment]
Found that `AdressPool.GetBuffer();` returns a buffer without content length and `AllocateAdress` does not set it either. This line at the end of  `AllocateAdress` fixes the problem: 

`adressSegment.SegmentPointer->Length = adressSegment.TotalLength;`


```
public RioBufferSegment AllocateAdress(IPEndPoint remoteAdress)
{
    Debug.Assert(inUse);
    var adressSegment = AdressPool.GetBuffer();
    SOCKADDR_INET* adress = (SOCKADDR_INET*)adressSegment.DataPointer;
    var adressBytes = remoteAdress.Address.GetAddressBytes();

    if (remoteAdress.AddressFamily == System.Net.Sockets.AddressFamily.InterNetwork)
    {
        adress->Ipv4.sin_family = ADDRESS_FAMILIES.AF_INET;
        adress->Ipv4.sin_port = WinSock.htons((ushort)remoteAdress.Port);

        fixed (byte* a = adressBytes)
            Unsafe.CopyBlock(adress->Ipv4.sin_addr.Address, a, (uint)adressBytes.Length);
    }
    adressSegment.SegmentPointer->Length = adressSegment.TotalLength;
    return adressSegment;
}
```

**Comment by aL3891** [comment]
Great, thanks! sorry I haven't kept up with the repo, it should probably be changed to use span now instead
